baseURL = "https://blog.desecho.org"
languageCode = "en-us"
title = "IT Blog"
theme = "minimal"
disqusShortname = "desechosblog"
googleAnalytics = "UA-655582-4"
enableEmoji = "true"

# Number of blog posts in each pagination page
paginate = 100

[permalinks]
post = "/blog/:year-:month-:day-:title/"

[params]
    author = "Anton Samarchyan"
    trancate = false
    description = ""
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["python", "javascript", "bash"]
    defaultKeywords = ["it" , "blog" , "web development" , "python", "ubuntu", "mac os", "javascript", "windows", "linux"]

[[menu.main]]
    url = "/"
    name = "IT Blog"
    weight = 1

[[menu.main]]
    url = "/posts/"
    name = "Posts"
    weight = 2

[[menu.main]]
    url = "/categories/"
    name = "Categories"
    weight = 2

[[menu.main]]
    url = "https://desecho.org"
    name = "desecho.org"
    weight = 3

[blackfriday]
  hrefTargetBlank = true # open the external links in a new window
