---
name: Deployment
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  deployment:
    name: Deployment
    runs-on: ubuntu-latest
    env:
      PROJECT: blog
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 15.x
          registry-url: https://registry.npmjs.org

      - name: Use npm cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm

      - name: Use pip cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: pip

      - name: Install linters
        run: |
          pip install restructuredtext_lint yamllint
          make install-shfmt
          make install-hadolint
          sudo npm install -g markdownlint-cli

      - name: Run linters
        run: make lint

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and push docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Install kubectl
        uses: azure/setup-kubectl@v2.1

      - name: Configure kubectl
        run: |
          mkdir ~/.kube
          echo $KUBECONFIG > ~/.kube/config
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}  # Done as a variable because doesn't work in place.

      - name: Deploy
        run: |
          kubectl apply -f deployment/deployment.yaml
          kubectl apply -f deployment/ingress.yaml
          kubectl apply -f deployment/service.yaml
          kubectl rollout restart "deployment/$PROJECT"
          kubectl rollout status "deployment/$PROJECT"
