---
name: Destruction
on: workflow_dispatch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  destruction:
    name: Destruction
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.6.0

      - name: Install kubectl
        uses: azure/setup-kubectl@v3.2

      - name: Configure kubectl
        run: |
          mkdir ~/.kube
          echo "$KUBECONFIG" > ~/.kube/config
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }} # Done as a variable because it doesn't work in place.

      - name: Install doctl
        uses: digitalocean/action-doctl@v2.2.0
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Destroy
        run: |
          kubectl delete -f deployment/deployment.yaml --ignore-not-found
          kubectl delete -f deployment/ingress.yaml --ignore-not-found
          kubectl delete -f deployment/service.yaml --ignore-not-found
