---
name: Find Broken Links
on:
  schedule:
    - cron: "0 4 1 * *" # runs at 04:00 UTC (00:00 EDT) on the first day of the month.
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  find_broken_links:
    name: Find Broken Links
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.4

      - name: Set up Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20.x
          registry-url: https://registry.npmjs.org

      - name: Use npm cache
        uses: actions/cache@v4.0.2
        with:
          path: ~/.npm
          key: npm

      - name: Install requirements
        run: npm install markdown-link-check -g

      - name: Find Broken Links
        run: make find-broken-links
